sudo: false
language: rust
os:
  - linux
  - osx
rust:
  - stable
  - nightly
  - beta
  
env:
  - FEATURES=default
  - FEATURES=rust-native-tls
script:
- cargo build --no-default-features --features "$FEATURES"
- cargo test
- cd github-gql-rs
- cargo build --no-default-features --features "$FEATURES"
- cargo test
