sudo: false
language: rust
os:
  - linux
  - osx
rust:
  - stable
env:
  - FEATURES=default
  - FEATURES=rust-native-tls
script:
- cargo build --no-default-features --features "$FEATURES"
- cd github-gql-rs
- cargo build --no-default-features --features "$FEATURES"
