sudo: false
language: rust
os:
- linux
- osx
rust:
- stable
- beta
- nightly
matrix:
  allow_failures:
    - rust: 
      - beta
      - nightly
  fast_finish: true    
env:
- FEATURES=default
- FEATURES=rust-native-tls
before_install:
- openssl aes-256-cbc -K $encrypted_b63566236b41_key -iv $encrypted_b63566236b41_iv
  -in auth_token.enc -out tests/auth_token -d
- cp tests/auth_token github-gql-rs/tests/auth_token
script:
- cargo build --no-default-features --features "$FEATURES"
- cargo test
- cd github-gql-rs
- cargo build --no-default-features --features "$FEATURES"
- cargo test
