[package]
name = "github_rs_compile_tests"
version = "0.1.0"

[features]
default = ["github-rs/default"]
rust-native-tls = ["github-rs/rust-native-tls"]

[dependencies]
compiletest_rs = "0.3"
github-rs = { version = "*", path = "../", default-features = false, optional = true }

